version: '3'
services:
  #
  # 1. RIMBOT
  #
  rimbot:
    env_file: ./cmd/rimbot/.env
    build: 
      context: .
      dockerfile: ./cmd/rimbot/Dockerfile
    
    depends_on: 
      - currencyservice
      
    ports: 
      - "${RIMBOT_PORT}:${RIMBOT_PORT}"  
  #
  # 2. CURRENCYSERVICE  
  #
  currencyservice:
    env_file: ./cmd/currencyservice/.env
    build:
      context: .
      dockerfile: ./cmd/currencyservice/Dockerfile
    
    expose:
      - "${CURRENCY_PORT}"
    depends_on: 
      - mongo  
  #
  # 3. FIXERWORKER 
  #
  fixerworker:
    env_file: ./cmd/fixerworker/.env
    build: 
      context: .
      dockerfile: ./cmd/fixerworker/Dockerfile

    depends_on: 
      - mongo  
  #
  # 4. MONGO 
  #
  mongo:
    image: mongo:latest
    expose:
      - "${MONGO_PORT}"
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
