package main

import (
	"time"
)

type currency struct{}

type currencySubscription struct {

	// RESTHook Standard fields
	id        int // autogenerated
	EventName string
	User      string
	TargetURL string
	Active    bool

	// APP Specific fields

	Base   currency
	Target currency
	Min    float32
	Max    float32
}

type currencyTicker struct {
	_id   string
	Base  currency
	Date  time.Time
	Rates map[currency]float32
}

type event struct {
	id             string // autogenerated
	Name           string
	PayloadExample string // JSON Example of reponse
}

// Method  Route   About
// GET /api/v1/subscription/   list subscriptions
// POST    /api/v1/subscription/   create a subscription
// GET /api/v1/subscription/:id/   get a subscription
// PUT /api/v1/subscription/:id/   update a subscription
// DELETE  /api/v1/subscription/:id/   delete a subscription
