

type CurrencySubscription struct {

    // RESTHook Standard fields

    id int         // autogenerated
    EventName string
    User string
    TargetURL URL
    Active bool 

    // APP Specific fields

    Base Currency
    Target Currency
    Min float
    Max float
}

type CurrencyTicker struct {
    _id string
    Base Currency
    Date Datetime 
    Rates map[Currency] float
}

type Event struct {
    id string        // autogenerated
    Name string
    PayloadExample string  // JSON Example of reponse
}

// Method  Route   About
// GET /api/v1/subscription/   list subscriptions
// POST    /api/v1/subscription/   create a subscription
// GET /api/v1/subscription/:id/   get a subscription
// PUT /api/v1/subscription/:id/   update a subscription
// DELETE  /api/v1/subscription/:id/   delete a subscription